### ISSUE TITLE
How to extract password ?

### ISSUE THREAD

**Issue by elpaxel** [nampud/oprah-proxy#1]
In your comment you said that you searched for the known part (se0316:ApiDigest:) in Process Hacker. But I tried like 100 times and didn't find it. Maybe you have found new way ?

**Comment by nampud** [comment]
I'm not really sure about the exact steps TBH. It was a long time since I had to extract the key. The current key still seems to be working fine. (This repo has the key already embedded in the code, you don't need to supply it yourself)
